# -*- coding: utf-8 -*-
"""KG-schema-evolution

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/aaryaupi/kg-schema-evolution.b2ad50a1-8f0b-47a1-beac-fb4671bd35bc.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260317/auto/storage/goog4_request%26X-Goog-Date%3D20260317T045652Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D454a433de7c86b7ec3f88eca2eb527f32988a4bb792b8571149ae57249b1f9f7ff5535e39c77760ac20a3cb0776e0b1d356afff3cb110627b7baa4f8d959752d609be02556510b5340425d65a9c46b3022c960004113857c3415c33a264b808cfbfccd662b46cb6a6b9ca1cb137b6dd57ad8c272deaa15fc9626deacd12ce8373b8c61e3deedfbca6d29bbf1389978a97479b688f4063719ef757d7a47ea4b2eae2e1737c2c14ba5954ab6f62dd123a3286dba1a6353e08720b92409b30ff870542c9b4b8fd4f1f72548a5d251ff771d7cf46821503df65f1ca2a5e6eed0f2b73a50fb0d049e976888c27b01fe2e708bcc2c2b7ad4dcaca377e641c18526a682
"""

# !pip install pykeen -q

from pykeen.datasets import Nations
dataset = Nations()
print(dataset.summary_str())

"""
The output is that we habe 14 entities and 55 relations a total of 1992 triples in the Nations dataset
"""

import pandas as pd
triples = dataset.training.mapped_triples
factory = dataset.training

df = pd.DataFrame(
    factory.triples,
    columns = ["head" ,"relation","tail"]

)

print(df.head())

print(df["relation"].nunique)
print(pd.concat([df["head"], df["tail"]]).unique())

from pykeen.pipeline import pipeline

result = pipeline(dataset ="Nations",
                 model = "TransH",
                 training_kwargs = dict(num_epochs = 50),
                 random_seed = 42)

import torch
import torch.nn.functional as F

model = result.model
entity_embeddings = model.entity_representations[0](indices =  None).detach()
entity_labels = dataset.training.entity_id_to_label

target = "india"
target_id = dataset.training.entity_to_id[target]
target_vec = entity_embeddings[target_id]

simillarity = F.cosine_similarity(target_vec.unsqueeze(0),entity_embeddings)
top5 = torch.topk(simillarity , k = 10)

print(f"Nearest neighbors to '{target}':")
for idx, score in zip(top5.indices.tolist(), top5.values.tolist()):
    label = entity_labels[idx]
    print(f"  {label:20s}  sim={score:.4f}")

# pick two countries you expect to be similar
a = "usa"
b = "uk"
c = "china"

def get_vec(name):
    idx = dataset.training.entity_to_id[name]
    return entity_embeddings[idx]

sim_ab = F.cosine_similarity(get_vec(a).unsqueeze(0), get_vec(b).unsqueeze(0))
sim_ac = F.cosine_similarity(get_vec(a).unsqueeze(0), get_vec(c).unsqueeze(0))

print(f"sim({a}, {b}) = {sim_ab.item():.4f}")
print(f"sim({a}, {c}) = {sim_ac.item():.4f}")